### ISSUE TITLE
Make clickable website link under User Profiles

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-2#728] opened 2021-03-28 19:06 UTC
As a donor I want to know more about a project when deciding whether to fund it.

I look at the Handshake project and there aren't any links to more information in the description.
So I click on the Creator name to view their profile..
![image](https://user-images.githubusercontent.com/39466970/112764411-3d010500-8fbd-11eb-9579-ec0295af1f5f.png)

 and see a link under the name that I am not permitted to highlight and copy, but I can click! HOWEVER.. clicking it returns an error page:
![image](https://user-images.githubusercontent.com/39466970/112764386-25c21780-8fbd-11eb-98c9-b6689fc637a5.png)

## 📋 Anything to add?
It would be even better to ALSO have a clickable link field in the project description.
Either a separate field as part of project creation or[ this issue](https://github.com/Giveth/giveth-2/issues/391) addressed that makes project description field more robust with the ability to format text including adding clickable links.

## ❓ Why is it important?
As a donor I am discouraged from contributing by the lack of ability to easily research a project.

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by jamespfarrell** [comment] 2021-04-07 19:47
The cause of this issue is that we aren't standardising the saving of website URLs when we save the profile URL.

Garbage in = garbage our, as they say.

**Comment by jamespfarrell** [comment] 2021-04-07 19:54
I have manually updated all urls in the live database, staging and dev may continue to be broken.

@mateodaza will add validation on the profile field.

**Comment by Danibelle** [comment] 2021-04-07 20:58
So many ways to do better, one thing at a time ;)

**Comment by divine-comedian** [comment] 2021-04-13 15:38
I'm testing the feature here to add validation to the website field on my user profile.

I can't seem to add a website to my profile now. 
@mateodaza 
![image](https://user-images.githubusercontent.com/67759413/114580068-89e70b80-9c4c-11eb-88e1-b92b1e3a3239.png)
![image](https://user-images.githubusercontent.com/67759413/114580221-aa16ca80-9c4c-11eb-9c09-7c3ec8da1a81.png)

**Comment by mateodaza** [comment] 2021-04-13 15:39
Weird, I'll take a look

**Comment by laurenluz** [comment] 2021-04-15 23:46
I was able to add my email to my profile no problem.

Also I checked Dani's profile to follow the link to her site and it worked just fine:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/97337b70-b3f5-447c-ab86-855e978b654f)

I tried it with mine though... and it looks like since I copy/pasted the whole URL into the "my website" spot... clicking it open makes the URL formatting weird "https://https//www.youtube.com/"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6234a072-4936-4b1d-a5e1-26c0a7e9d85b)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6dd640f9-5a30-4953-b45f-be917392267e)

**Comment by mateodaza** [comment] 2021-04-16 00:33
Thank you! Fixed now

**Comment by divine-comedian** [comment] 2021-04-22 16:28
Following up with Lauren's issue I can now successfully navigate to youtube from her profile. 

![image](https://user-images.githubusercontent.com/67759413/115750249-f73e1f00-a365-11eb-8599-af63fccabc04.png)

Hooray!

I also no longer have any issues trying to update my website on my profile. Looks like we can put this one to bed! (Just one more cat video though..)

**Closed** 2021-05-05 20:02 UTC
Labels: bug, prioritise me
