### ISSUE TITLE
Send image data on create project flow

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-2#137] opened 2020-10-13 12:49 UTC
When user creates a project, the image field is path to image. We should fill that entry with image data (base64 type maybe)

**Comment by brymut** [comment] 2020-10-13 12:51
Was just looking at this. Can switch this over, but was thinking, do we need the filename?

**Comment by brymut** [comment] 2020-10-21 14:32
@aminlatifi, should we still leave in the rest of the pinata stuff in the frontend or is there another use for it?

**Comment by aminlatifi** [comment] 2020-10-21 14:38
> @aminlatifi, should we still leave in the rest of the pinata stuff in the frontend or is there another use for it?

We can remove pinata part.

**Comment by aminlatifi** [comment] 2020-10-27 15:59
I just noticed still old `addProjectSimple` is used on UI. I tried to adapt new `addProject`, but it seems the onSubmit doesn't call mutation. @brymut Are you sure UI is working and sends project data after data is submitted? I updated frontend under this branch https://github.com/Giveth/giveth-2/tree/create-project-flow-update 
It's incomplete probably, would you please update it to work correctly with backend

**Comment by brymut** [comment] 2020-10-27 16:03
Yes, that's exactly what I'm working on locally. It was, but I broke it moving some stuff around, was just about to push a similar change switching to the `addProject` mutation since I can use it now. That's why I merged the recent PR I had jus now.

**Comment by aminlatifi** [comment] 2020-10-27 16:09
I would go forward on file uploading on separate testing page, then will ask you to adapt it on create project flow.

**Comment by brymut** [comment] 2020-10-27 16:44
alright, sorry for being out of sync

**Comment by brymut** [comment] 2020-10-27 16:46
will update my changes to reflect your way from the changes you've pushed to the branch you've linked.

**Comment by GriffGreen** [comment] 2020-10-28 15:53
Pin the 4 images that Marko made in advance so it doesn't need to be pinned every time? 

It's not a big deal if we make them upload it again... It's a tough decision... @aminlatifi is looking at it?

**Comment by GriffGreen** [comment] 2020-10-28 15:54
Could also use gatsby images and put them in the images folder... using the same patternd we use for other graphics on the site... but maybe it makes more sense to have it as a static image...

**Comment by GriffGreen** [comment] 2020-10-28 15:55
We will need to define another entry into the graphql so we have a static string and during create project one of the 2 options are filled... either a static string or an IPFS image

**Comment by GriffGreen** [comment] 2020-10-28 15:56
Should it be copied as SVG?

Kay needs to push something... but you can export as SVG

Make a check to make sure that when you are exporting the file that it is actually SVG!!

**Comment by aminlatifi** [comment] 2020-10-29 15:25
@brymut backend is ready to upload
https://github.com/Giveth/giveth-2/issues/97#issuecomment-718827481

**Comment by mateodaza** [comment] 2020-11-10 22:13
I found a bug on the implementation, if the image field on addProject is sent empty or null, it still uploads something. 

For example https://gateway.pinata.cloud/ipfs/QmTSZQG6Kr4hZVsBV3YjUqvsMy4hEBEA66CUmoKEcN4L6J

**Comment by aminlatifi** [comment] 2020-11-11 09:21
@mateodaza Did you use GraphQL playground? or it happened on UI?
We don't have `image` field on mutation, there are two fields `imageUpload` and 'imageStatic` for different purposes.

**Comment by brymut** [comment] 2020-11-11 09:24
Hmm, interesting. I cant reproduce, maybe I'm missing something. Might you know what is being uploaded?

**Comment by aminlatifi** [comment] 2020-11-11 09:25
@brymut It's the content of what has been uploaded!
```
<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta http-equiv="x-ua-compatible" content="ie=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="note" content="environment=development"/><title data-react-helmet="true"></title><link rel="icon" href="/favicon.svg?v=1cc5a03a8605127ccf99c0dd98e90f4e" type="image/svg+xml"/><link rel="icon" href="/favicon-32x32.png?v=1cc5a03a8605127ccf99c0dd98e90f4e" type="image/png"/><link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous"/><meta name="theme-color" content="#663399"/><link rel="apple-touch-icon" sizes="48x48" href="/icons/icon-48x48.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="72x72" href="/icons/icon-72x72.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="96x96" href="/icons/icon-96x96.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="144x144" href="/icons/icon-144x144.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="256x256" href="/icons/icon-256x256.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="384x384" href="/icons/icon-384x384.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png?v=1cc5a03a8605127ccf99c0dd98e90f4e"/><link href="https://fonts.googleapis.com/css?family=Red+Hat+Display|Red+Hat+Text" rel="stylesheet"/><script src="/socket.io/socket.io.js"></script></head><body><script>(function() { try {
  var mode = localStorage.getItem('theme-ui-color-mode');
  if (!mode) return
  document.body.classList.add('theme-ui-' + mode);
} catch (e) {} })();</script><div id="___gatsby"></div><script src="/polyfill.js" nomodule=""></script><script src="/commons.js"></script></body></html>
```

**Comment by aminlatifi** [comment] 2020-11-11 09:26
I guess something on UI has happened!

**Comment by brymut** [comment] 2020-11-11 09:36
Ok, will try to check it out and see what is happening because I'm currently clueless

**Comment by mateodaza** [comment] 2020-11-11 11:04
> @mateodaza Did you use GraphQL playground? or it happened on UI?
> 
> We don't have `image` field on mutation, there are two fields `imageUpload` and 'imageStatic` for different purposes.
> 
> 

It happened on UI on my local env

**Comment by papermache** [comment] 2020-11-18 16:10
Fix by Sunday or @mateodaza will do it.

**Closed** 2020-11-22 10:23 UTC
