### ISSUE TITLE
I donated to Giveth project and the funds were taken from my wallet but it doesnt show up on the project page or in my donations..

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#344] opened 2021-01-12 17:24 UTC
## 📋 Anything to add?
I donated 0.048 ropsten eth to the Giveth project using 0x7554f10Da3Ed7128300577e55abCd8F8835BCee4 in meta mask. The funds were taken from my wallet but the transaction looks like this on etherscan
https://etherscan.io/tx/0xb112aa44edbb5b5cc00622e3f342310e22a97e4388f3ebe199285d46aae742cb
and it shows no donations on the project page
![image](https://user-images.githubusercontent.com/74267818/104349449-8e265000-54c8-11eb-8810-09b425feedba.png)
And no donations on the my donations page
![image](https://user-images.githubusercontent.com/74267818/104349510-a1392000-54c8-11eb-89f6-d69a14dfb05e.png)

**Comment by mateodaza** [comment] 2021-01-12 17:40
Here's the tx in ropsten etherscan https://ropsten.etherscan.io/tx/0xb112aa44edbb5b5cc00622e3f342310e22a97e4388f3ebe199285d46aae742cb

 The donation did happen! But you used metamask instead of torus wallet. Your account is linked with torus, not metamask. This will be a feature to build in the future

**Comment by mateodaza** [comment] 2021-01-12 17:49
Will see what's going on with the donations not appearing on the project's view

**Comment by mateodaza** [comment] 2021-01-12 17:52
@jamespfarrell this is shown right now when a donation is made 

"No repository for "Wallet" was found. Looks like this entity is not registered in current "default" connection?" through saveDonation mutation

**Comment by mateodaza** [comment] 2021-01-12 18:26
Can this be related? https://github.com/typeorm/typeorm/issues/3017  on the impact graph @jamespfarrell

**Comment by jamespfarrell** [comment] 2021-01-12 18:57
This should still show the donation on the donations page, even if it was made with Metamask

**Comment by tommygiveth** [comment] 2021-01-12 19:11
I donated to Grey Water project with Metamask and Torus almost 2 hours ago also

**Comment by WhyldWanderer** [comment] 2021-01-12 19:26
The funds that were donated to my project (diamante grey water) dont show up on the donations section of the project page.. but they do show up in my total value of assets in wallet section of my account.

![image](https://user-images.githubusercontent.com/74267818/104362699-c2563c80-54d9-11eb-9778-21ae33ea2cb6.png)

**Comment by jamespfarrell** [comment] 2021-01-12 20:47
Ok this is fixed now.

Please note, you immediately click on 'view my donations'
![image](https://user-images.githubusercontent.com/10499048/104370643-762deb00-551f-11eb-9057-3464cca4ca6a.png)

The donation won't show up until it's confirmed on the blockchain, so 
![image](https://user-images.githubusercontent.com/10499048/104370793-abd2d400-551f-11eb-932b-d389e7df6da2.png)

then later:
![image](https://user-images.githubusercontent.com/10499048/104370845-bb521d00-551f-11eb-9a97-84354087f497.png)

**Comment by jamespfarrell** [comment] 2021-01-12 20:51
Also updated the etherscan link

**Comment by laurenluz** [comment] 2021-01-17 19:41
Donated to a few projects and it all seems to be working fine! And super fast! Money comes out of my wallet, shows up in donations. It's recorded under my account, etc. 

I think this is done.

**Closed** 2021-02-07 22:12 UTC
