### ISSUE TITLE
When I donate on next.giveth.io... The donation in progress spinner does not stop

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-2#882] opened 2021-05-20 17:35 UTC
Testing on next.giveth.io in chrome with metamask

After i confirm the transaction to donate to a project, The donation in progress notice pops up but does not go away once the transaction has been completed.
![image](https://user-images.githubusercontent.com/74267818/119023636-6d32a780-b95f-11eb-84d8-a8f5088fe49c.png)
![image](https://user-images.githubusercontent.com/74267818/119023662-73288880-b95f-11eb-9287-57992fb4d976.png)

**Comment by mateodaza** [comment] 2021-05-20 22:38
This is now fixed, even though we are having an error coming from Infura saying "Returned error: rejected due to project ID settings" on ropsten - in general ropsten has been working very weirdly lately but anyway, I set a better notice for these cases, donations are now being saved and it shows an "unconfirmed" modal for these cases, where the donation is saved and with an tx hash not yet included in the blockchain

**Comment by divine-comedian** [comment] 2021-05-26 18:00
testing next.giveth 
brave browser, clean cache on MM

I didn't have any issue making a donation on ropsten just now. Perhaps the network problems have been resolved.
I did notice the modal before but unortunately the transaction was too fast and it didn't pop-up this time so I couldn't screenshot it
Unless there's a better way to test this issue I'm going to mark it as resolved. 
![image](https://user-images.githubusercontent.com/67759413/119708719-6ce84f80-be2a-11eb-853b-1b38ecac24f2.png)

**Closed as completed** 2021-06-09 17:58 UTC
